AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: SAM Template for Common AWS Infrastructure

Parameters:
  Stage:
    Type: String

Resources:
  UserLoggedInFanoutTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub UserLoggedInFanout-${Stage}
  
  ExpenseServiceFunctionWarmingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub SplitsiesExpenseServiceFunctionWarming-${Stage}
      VisibilityTimeout: 60
  
  OcrServiceFunctionWarmingQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub SplitsiesOcrServiceFunctionWarming-${Stage}
      VisibilityTimeout: 30
  
  ExpenseServiceFunctionWarmingQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref UserLoggedInFanoutTopic
      Endpoint: !GetAtt ExpenseServiceFunctionWarmingQueue.Arn
      RawMessageDelivery: true
  
  OcrServiceFunctionWarmingQueueSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: sqs
      TopicArn: !Ref UserLoggedInFanoutTopic
      Endpoint: !GetAtt OcrServiceFunctionWarmingQueue.Arn
      RawMessageDelivery: true
  
  ExpenseServiceFunctionWarmingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref ExpenseServiceFunctionWarmingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt ExpenseServiceFunctionWarmingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UserLoggedInFanoutTopic

  OcrServiceFunctionWarmingQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref OcrServiceFunctionWarmingQueue
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal: "*"
            Action: sqs:SendMessage
            Resource: !GetAtt OcrServiceFunctionWarmingQueue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn: !Ref UserLoggedInFanoutTopic

Outputs:
  SNSTopicArn:
    Description: ARN of the UserLoggedInFanoutTopic
    Value: !Ref UserLoggedInFanoutTopic
  Queue1Arn:
    Description: ARN of the ExpenseServiceFunctionWarmingQueue
    Value: !GetAtt ExpenseServiceFunctionWarmingQueue.Arn
  Queue2Arn:
    Description: ARN of the OcrServiceFunctionWarmingQueue
    Value: !GetAtt OcrServiceFunctionWarmingQueue.Arn